version: '3'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "4200:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro 

  python-backend:
    image: registry.gitlab.com/chillredchilli/hackinglab-tfm-images/python-backend
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PATH=/python/
      - VIRTUAL_DEST=/
      - VIRTUAL_PORT=80

  java-backend:
    image: registry.gitlab.com/chillredchilli/hackinglab-tfm-images/java-backend
    expose:
      - "8080"
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PATH=/java/
      - VIRTUAL_DEST=/
      - VIRTUAL_PORT=8080
    depends_on:
      - nginx-proxy

  hackingLab:
    image: registry.gitlab.com/chillredchilli/hackinglab-tfm-images/frontend
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PATH=/
      - VIRTUAL_PORT=80
    depends_on:
      - nginx-proxy
      - java-backend
      - python-backend